<a href="https://colab.research.google.com/github/larialbu/curso_machine_learning_senac/blob/main/atividade_aula_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercícios - Aula 06

##Numpy

##arange()
### arange() funciona como o range() do python

In [1]:

import numpy as np


In [2]:

arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:

arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:

arr3 = np.arange(10, 20, 2)
arr3

array([10, 12, 14, 16, 18])

In [5]:

arr4 = np.arange(10, 20, 1.4)
arr4
     

array([10. , 11.4, 12.8, 14.2, 15.6, 17. , 18.4, 19.8])

##linspace()
###linspace() recebe o valor inicial, o valor final e a quantidade de elementos numéricos que se quer entre os dois valores.

In [6]:

arr5 = np.linspace(10, 20, 11)
display(arr5)
len(arr5)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

11

In [7]:

arr6 = np.linspace(10, 20, 101)
display(arr6)
len(arr6)

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

101

In [8]:

arr7 = np.linspace(0, np.pi, 100)
display(arr7)
len(arr7)
     

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

100

##Matrizes
###criando matrizes

In [9]:

minhaMatriz = np.array([[1,2,3],
                       [4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:

minhaMatriz = np.array([[1,2,3],[4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:

minhaLista = [[13,81,22],[0,34,59],[21,48,94]]
minhaLista

[[13, 81, 22], [0, 34, 59], [21, 48, 94]]

In [12]:

minhaMatriz = np.matrix(minhaLista)
minhaMatriz


matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

##zeros()
###np.zeros() pode formar tanto vetores quanto matrizes preenchidos com o valor 0

In [13]:
# Vetor
print(np.zeros(3))

[0. 0. 0.]


In [14]:

x = np.zeros(3)
x

array([0., 0., 0.])

In [15]:

# Matriz
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:

x = np.zeros((3,2))
x
     

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

ones()
Cria uma matriz ou um vetor e preenche com 1.


In [17]:

x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:

x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

#Desafio 01
###Matriz 4x4 com apenas numeros 8.

In [19]:

x = np.ones((4,4))
x = x*8
x

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

##diag()
###Os valores passados como parametros informam a diagonal e o restante será preenchido por 0

In [20]:

z = np.diag(np.array([1,2,3,4,5,6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

##eye()
###Forma uma matriz identidade da ordem do valor passado como argumento.

In [21]:

y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# Definindo o tipo
y = np.eye(5, dtype= int)
y
     

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

##shape()
###verifica o fomrato da matriz. Existem duas formas:

In [23]:
np.shape(minhaMatriz)

(3, 3)

In [24]:

minhaMatriz.shape

(3, 3)

#Utilidades

In [26]:

# Verifica o tipo da matriz
type(minhaMatriz)
     

numpy.matrix

In [27]:

# Verifica o tipo dos dados da matriz
minhaMatriz.dtype
     

dtype('int64')

In [28]:

# Selecionando elementos da matriz
minhaMatriz[2,1]

48

In [29]:
# Selecionando a primeira linha da matriz
print(minhaMatriz[0,:])

[[13 81 22]]


In [30]:

# Selecionando a terceira coluna da matriz
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


In [31]:
# Alterando um elemento da matriz
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

#Operações basicas

In [32]:
meuArray = np.arange(1,10)

In [33]:
# Soma dos valores do array
np.sum(meuArray)

45

In [34]:
# Ibtendo o produto
np.prod(meuArray)

362880

In [35]:
# Soma acumulada
np.cumsum(meuArray)
     

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [36]:

# Valor minimo
meuArray.min()

1

In [37]:

# Valor Maximo
meuArray.max()

9

#Operações estatisticas básicas

In [38]:

# Obtendo a média
np.mean(meuArray)
     

5.0

In [39]:

# Obtendo a mediana
np.median(meuArray)
     

5.0

In [40]:
# Obtendo a variança dos valores
np.var(meuArray)
     

6.666666666666667

In [41]:

# Obtendo o desvio padrão
np.std(meuArray)
     

2.581988897471611

#Desafio 02

In [42]:
# Criando o array
teste = np.arange(1,10)
teste

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
pares = np.where(teste % 2 == 0)
for i in pares:
  print(teste[i], end= ' ')

[2 4 6 8] 

In [44]:
# Varrendo o array para obter os impares:
impares = np.where(teste % 2 == 1)
for i in impares:
  print(teste[i], end= ' ')
     

[1 3 5 7 9] 

In [46]:
#media, soma, produtos, variancia, desvio padrão
print('Média:', np.mean(teste))
print('Soma:', np.sum(teste))
print('Produto:', np.prod(teste))
print('Variancia:', np.var(teste))
print('Desvio padrão', np.std(teste))

Média: 5.0
Soma: 45
Produto: 362880
Variancia: 6.666666666666667
Desvio padrão 2.581988897471611
